name: kelechek
description: Kelechek
version: 1.0.0+6
publish_to: 'none'

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  credit_card_form:
    path: packages/flutter-credit-card-form
  flutter_chat_ui:
    path: packages/flutter_chat_ui
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  cached_network_image: ^3.3.1
  dotted_border: ^2.1.0
  get_it: ^7.6.7
  google_fonts: ^6.2.1
  image_picker: ^1.0.7
  internet_connection_checker_plus: ^2.2.0
  intl: ^0.18.1
  keyboard_dismisser: ^3.0.0
  modal_bottom_sheet: ^3.0.0
  equatable: ^2.0.5
  dropdown_button2: ^2.3.9
  flutter_screenutil: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  injectable: ^2.3.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  calendar_date_picker2: ^0.5.5
  permission_handler: ^11.3.0
  flash: ^3.1.0
  uuid: ^4.3.3
  lottie: ^3.1.0
  voice_message_package: ^2.1.4
  record: ^5.0.5
  file_picker: ^8.0.0+1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.6.0
  url_launcher: ^6.2.5
  flutter_native_splash: ^2.4.0
  dio: ^5.4.3+1
  fpdart: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  
  hive_generator: ^2.0.1
  mocktail: ^1.0.3
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  freezed: ^2.4.7



flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/svg/
    - assets/image/
    - assets/demo_content/
    - assets/lottie/
  
flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon/icon.png"
  android: true
  ios: true
  android_gravity: "center"
